node_level:
  save: false
  model_path: "pretrained_models/pubmed/full_model/node.pth"
  weight_path: "pretrained_models/pubmed/weights/node.pth"
  pretrained_weights: null
  pretrained: false
  plot: true
  title: null
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  drop_scheme: "degree"
  tau: 0.7
  num_epochs: 1800
  num_epochs_eval: 500
  num_classes: 3
  weight_decay: 0.00001
  batch: 64
  rd_seed: 129

proximity_level:
  save: false
  model_path: "pretrained_models/pubmed/full_model/proximity.pth"
  weight_path: "pretrained_models/pubmed/weights/proximity.pth"
  pretrained_weights: null
  pretrained: false
  plot: true
  title: null
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  drop_scheme: "degree"
  tau: 0.7
  walk_length: 5
  p: 1
  q: 1
  num_epochs: 800
  num_epochs_eval: 500
  num_classes: 3
  weight_decay: 0.00001
  batch: 256
  rd_seed: 129

cluster_level:
  save: false
  model_path: "pretrained_models/pubmed/full_model/cluster.pth"
  weight_path: "pretrained_models/pubmed/weights/cluster.pth"
  pretrained_weights: null
  pretrained: false
  plot: true
  title: null
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  drop_scheme: "degree"
  tau: 0.7
  num_epochs: 1000
  num_epochs_eval: 500
  num_classes: 3
  weight_decay: 0.00001
  rd_seed: 129

graph_level: 
  save: false
  model_path: "pretrained_models/pubmed/full_model/graph.pth"
  weight_path: "pretrained_models/pubmed/weights/graph.pth"
  pretrained_weights: null
  pretrained: false
  plot: true
  title: null
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  drop_scheme: "degree"
  tau: 0.7
  num_epochs: 2000
  num_epochs_eval: 500
  num_classes: 3
  weight_decay: 0.00001
  rd_seed: 129