node_level:
  save: false
  model_path: "pretrained_models/citeseer/full_model/node.pth"
  weight_path: "pretrained_models/citeseer/weights/node.pth"
  pretrained_weights: null
  pretrained: false
  plot: true
  title: null
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  drop_scheme: "degree"
  tau: 0.9
  num_epochs: 200
  num_epochs_eval: 500
  num_classes: 6
  weight_decay: 0.00001
  batch: 0
  rd_seed: 129

proximity_level:
  save: false
  model_path: "pretrained_models/citeseer/full_model/proximity.pth"
  weight_path: "pretrained_models/citeseer/weights/proximity.pth"
  pretrained_weights: null
  pretrained: false
  plot: true
  title: null
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  drop_scheme: "degree"
  tau: 0.9
  walk_length: 3
  p: 1
  q: 1
  num_epochs: 200
  num_epochs_eval: 500
  num_classes: 6
  weight_decay: 0.00001
  batch: 0
  rd_seed: 129

cluster_level:
  save: false
  model_path: "pretrained_models/citeseer/full_model/cluster.pth"
  weight_path: "pretrained_models/citeseer/weights/cluster.pth"
  pretrained_weights: null
  pretrained: false
  plot: true
  title: null
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  drop_scheme: "evc"
  tau: 0.9
  num_epochs: 200
  num_epochs_eval: 500
  num_classes: 6
  weight_decay: 0.00001
  rd_seed: 129

graph_level: 
  save: false
  model_path: "pretrained_models/citeseer/full_model/graph.pth"
  weight_path: "pretrained_models/citeseer/weights/graph.pth"
  pretrained_weights: null
  pretrained: false
  plot: true
  title: null
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  drop_scheme: "degree"
  tau: 0.9
  num_epochs: 200
  num_epochs_eval: 500
  num_classes: 6
  weight_decay: 0.00001
  rd_seed: 129